site_name: My Note

# repo_url: https://github.com/mjw879/my-note
# repo_name: mjw879/my-note

nav:
  - Home: index.md
  - LeetCode:
    - 数学: LeetCode/数学.md
    - 前缀和: LeetCode/前缀和.md
    - 桶排序: LeetCode/桶排序.md
    - 二叉树: LeetCode/二叉树.md
    - 字符串: LeetCode/字符串.md
    - 随机采样: LeetCode/随机采样.md
    - 深度优先搜索: LeetCode/BFS.md
    - 二分法: LeetCode/二分法.md
    - 枚举: LeetCode/枚举.md
    - 脑筋急转弯: LeetCode/脑筋急转弯.md
    - 思路转换: LeetCode/思路转换.md
    - 贪心: LeetCode/贪心.md
    - 图: LeetCode/图.md
    - 动态规划: 
      - 动态规划: LeetCode/dp/index.md
      - 动态规划基础: LeetCode/dp/dp.md
      - 区间 DP: LeetCode/dp/interval.md
    - 栈: LeetCode/栈.md
    - 滑动窗口: LeetCode/滑动窗口.md
    - 数据结构: LeetCode/数据结构.md
    - 双指针: LeetCode/双指针.md
    - 并查集: LeetCode/并查集.md
  # - Algorithm:
  #   - 数据结构:
    

  - Git: Git/git.md
  - LaTex:  LaTex/LaTex.md
  # - Algorithm:
  #   - Algorithm/README.md 
  #   - Page 1: section/page-1.md
  #     - Page 1: 1. enuerate.md
  #   - Page 2: section/page-n.md

theme:
  name: material
  logo: 'resources/icon/notebook.svg'
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: deep purple
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs   # 导航栏
    # - navigation.expand # 默认展开左侧栏的子项
    - content.code.copy
    - navigation.indexes
    - navigation.top    # 返回顶部按钮
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html # 让 `??? tip` 折叠块里面可以显示 LaTex 公式
  - pymdownx.arithmatex: # 渲染公式
      generic: true
  - pymdownx.highlight: # 自动生成代码行号
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  # 支持emoji表情
  # - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript: # 渲染公式
  - resources/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# plugins:
#   - search: 
#       separator: '[\s\u200b\-]' # 中文搜索 require `pip3 install jieba`